"""initial

Revision ID: dd9600a52a20
Revises: 
Create Date: 2026-06-18 00:21:38.681404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9600a52a20'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父项ID'),
    sa.Column('level', sa.Integer(), nullable=True, comment='层级'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('description', sa.Text(), nullable=False, comment='原始描述（自由文本）'),
    sa.Column('normalized_name', sa.String(length=300), nullable=True, comment='AI标准化后名称'),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=True, comment='工程量'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='单位'),
    sa.Column('matched_quota_id', sa.Integer(), nullable=True, comment='匹配定额ID'),
    sa.Column('match_confidence', sa.Numeric(precision=5, scale=2), nullable=True, comment='匹配置信度'),
    sa.Column('match_method', sa.String(length=30), nullable=True, comment='匹配方法'),
    sa.Column('match_detail', sa.JSON(), nullable=True, comment='匹配详情（候选列表等）'),
    sa.Column('computed_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='计算价格'),
    sa.Column('manual_adjust_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='人工调整价格'),
    sa.Column('adjust_reason', sa.Text(), nullable=True, comment='调整原因'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_items_id'), 'bill_items', ['id'], unique=False)
    op.create_index(op.f('ix_bill_items_project_id'), 'bill_items', ['project_id'], unique=False)
    op.create_table('enterprise_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False, comment='企业ID'),
    sa.Column('item_code', sa.String(length=50), nullable=False, comment='工料机编码'),
    sa.Column('item_name', sa.String(length=200), nullable=False, comment='工料机名称'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='类别（人工/材料/机械）'),
    sa.Column('spec', sa.String(length=200), nullable=True, comment='规格型号'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='单位'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='单价'),
    sa.Column('labor_cost', sa.Numeric(precision=12, scale=2), nullable=True, comment='人工费'),
    sa.Column('material_cost', sa.Numeric(precision=12, scale=2), nullable=True, comment='材料费'),
    sa.Column('machinery_cost', sa.Numeric(precision=12, scale=2), nullable=True, comment='机械费'),
    sa.Column('effective_date', sa.Date(), nullable=False, comment='生效日期'),
    sa.Column('expire_date', sa.Date(), nullable=True, comment='失效日期'),
    sa.Column('version', sa.Integer(), nullable=True, comment='版本号'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_prices_enterprise_id'), 'enterprise_prices', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_enterprise_prices_id'), 'enterprise_prices', ['id'], unique=False)
    op.create_table('enterprises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='企业名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='企业编码'),
    sa.Column('contact', sa.String(length=50), nullable=True, comment='联系人'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('address', sa.Text(), nullable=True, comment='地址'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_enterprises_id'), 'enterprises', ['id'], unique=False)
    op.create_table('material_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False, comment='材料ID'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='单价'),
    sa.Column('source_type', sa.String(length=30), nullable=True, comment='来源类型（信息价/市场价/供应商报价）'),
    sa.Column('source_region', sa.String(length=100), nullable=True, comment='来源地区'),
    sa.Column('source_detail', sa.String(length=200), nullable=True, comment='来源详情'),
    sa.Column('price_date', sa.Date(), nullable=False, comment='价格日期'),
    sa.Column('supplier', sa.String(length=200), nullable=True, comment='供应商'),
    sa.Column('price_trend', sa.String(length=10), nullable=True, comment='价格趋势'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_prices_id'), 'material_prices', ['id'], unique=False)
    op.create_index(op.f('ix_material_prices_material_id'), 'material_prices', ['material_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=False, comment='材料编码'),
    sa.Column('material_name', sa.String(length=200), nullable=False, comment='材料名称'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID'),
    sa.Column('category_path', sa.String(length=500), nullable=True, comment='分类路径'),
    sa.Column('spec', sa.String(length=200), nullable=True, comment='规格型号'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='单位'),
    sa.Column('brand', sa.String(length=100), nullable=True, comment='品牌'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_code')
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_table('price_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False, comment='资源类型（enterprise/material）'),
    sa.Column('resource_id', sa.Integer(), nullable=False, comment='资源ID'),
    sa.Column('field_name', sa.String(length=50), nullable=True, comment='变更字段'),
    sa.Column('old_value', sa.Numeric(precision=12, scale=2), nullable=True, comment='旧值'),
    sa.Column('new_value', sa.Numeric(precision=12, scale=2), nullable=True, comment='新值'),
    sa.Column('change_reason', sa.String(length=500), nullable=True, comment='变更原因'),
    sa.Column('operator', sa.String(length=50), nullable=True, comment='操作人'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='扩展信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_histories_id'), 'price_histories', ['id'], unique=False)
    op.create_table('pricing_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('version', sa.Integer(), nullable=True, comment='版本号'),
    sa.Column('total_price', sa.Numeric(precision=14, scale=2), nullable=True, comment='总价'),
    sa.Column('labor_total', sa.Numeric(precision=14, scale=2), nullable=True, comment='人工费合计'),
    sa.Column('material_total', sa.Numeric(precision=14, scale=2), nullable=True, comment='材料费合计'),
    sa.Column('machinery_total', sa.Numeric(precision=14, scale=2), nullable=True, comment='机械费合计'),
    sa.Column('management_fee', sa.Numeric(precision=14, scale=2), nullable=True, comment='管理费'),
    sa.Column('profit', sa.Numeric(precision=14, scale=2), nullable=True, comment='利润'),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=True, comment='税金'),
    sa.Column('social_insurance', sa.Numeric(precision=14, scale=2), nullable=True, comment='规费'),
    sa.Column('adjustment_log', sa.JSON(), nullable=True, comment='调整记录（JSON数组）'),
    sa.Column('ai_suggestion', sa.Text(), nullable=True, comment='AI 调价建议'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_results_id'), 'pricing_results', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_results_project_id'), 'pricing_results', ['project_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False, comment='企业ID'),
    sa.Column('name', sa.String(length=300), nullable=False, comment='项目名称'),
    sa.Column('project_code', sa.String(length=50), nullable=True, comment='项目编码'),
    sa.Column('project_type', sa.String(length=100), nullable=True, comment='项目类型'),
    sa.Column('area', sa.Numeric(precision=10, scale=2), nullable=True, comment='建筑面积(m²)'),
    sa.Column('budget', sa.Numeric(precision=14, scale=2), nullable=True, comment='预算金额'),
    sa.Column('region', sa.String(length=100), nullable=True, comment='项目地区'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code')
    )
    op.create_index(op.f('ix_projects_enterprise_id'), 'projects', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('quota_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quota_id', sa.Integer(), nullable=False, comment='所属定额ID'),
    sa.Column('resource_code', sa.String(length=50), nullable=False, comment='资源编码'),
    sa.Column('resource_name', sa.String(length=200), nullable=False, comment='资源名称'),
    sa.Column('resource_type', sa.String(length=20), nullable=True, comment='资源类型（人工/材料/机械）'),
    sa.Column('spec', sa.String(length=200), nullable=True, comment='规格型号'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='单位'),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False, comment='消耗量'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='单价'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quota_items_id'), 'quota_items', ['id'], unique=False)
    op.create_index(op.f('ix_quota_items_quota_id'), 'quota_items', ['quota_id'], unique=False)
    op.create_table('quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quota_code', sa.String(length=50), nullable=False, comment='定额编码'),
    sa.Column('quota_name', sa.String(length=300), nullable=False, comment='定额名称'),
    sa.Column('work_type', sa.String(length=100), nullable=True, comment='工种类型'),
    sa.Column('decoration_type', sa.String(length=100), nullable=True, comment='装修类型'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='单位'),
    sa.Column('comprehensive_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='综合单价'),
    sa.Column('labor_consumption', sa.Numeric(precision=10, scale=4), nullable=True, comment='人工消耗量'),
    sa.Column('material_consumption', sa.Text(), nullable=True, comment='材料消耗（JSON）'),
    sa.Column('machinery_consumption', sa.Text(), nullable=True, comment='机械消耗（JSON）'),
    sa.Column('measurement_rules', sa.Text(), nullable=True, comment='计量规则'),
    sa.Column('work_content', sa.Text(), nullable=True, comment='工作内容'),
    sa.Column('reference_standard', sa.String(length=100), nullable=True, comment='参考标准'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quota_code')
    )
    op.create_index(op.f('ix_quotas_id'), 'quotas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotas_id'), table_name='quotas')
    op.drop_table('quotas')
    op.drop_index(op.f('ix_quota_items_quota_id'), table_name='quota_items')
    op.drop_index(op.f('ix_quota_items_id'), table_name='quota_items')
    op.drop_table('quota_items')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_enterprise_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_pricing_results_project_id'), table_name='pricing_results')
    op.drop_index(op.f('ix_pricing_results_id'), table_name='pricing_results')
    op.drop_table('pricing_results')
    op.drop_index(op.f('ix_price_histories_id'), table_name='price_histories')
    op.drop_table('price_histories')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_material_prices_material_id'), table_name='material_prices')
    op.drop_index(op.f('ix_material_prices_id'), table_name='material_prices')
    op.drop_table('material_prices')
    op.drop_index(op.f('ix_enterprises_id'), table_name='enterprises')
    op.drop_table('enterprises')
    op.drop_index(op.f('ix_enterprise_prices_id'), table_name='enterprise_prices')
    op.drop_index(op.f('ix_enterprise_prices_enterprise_id'), table_name='enterprise_prices')
    op.drop_table('enterprise_prices')
    op.drop_index(op.f('ix_bill_items_project_id'), table_name='bill_items')
    op.drop_index(op.f('ix_bill_items_id'), table_name='bill_items')
    op.drop_table('bill_items')
    # ### end Alembic commands ###
